apiVersion: apps/v1
kind: Deployment
metadata: { name: wordpress }
spec:
  replicas: 1
  selector: { matchLabels: { app: wordpress } }
  template:
    metadata: { labels: { app: wordpress } }
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.6-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql               # <- le DNS interne (module 7) !
        - name: WORDPRESS_DB_USER
          value: wpuser
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: { secretKeyRef: { name: mysql-secret, key: mysql-password } }
        - name: WORDPRESS_DB_NAME
          value: wordpress
        ports: [{ containerPort: 80 }]
        volumeMounts:
        - { name: html, mountPath: /var/www/html }
      volumes:
      - name: html
        persistentVolumeClaim: { claimName: wordpress-pvc }
