apiVersion: v1
kind: Secret
metadata: { name: mysql-secret }
type: Opaque
stringData:                          # stringData = on ecrit en clair, K8s encode
  mysql-root-password: "RootPass123"
  mysql-password: "WpPass123"
